CREATE SEQUENCE kolcsonzo_seq
START WITH 6
INCREMENT BY 1;

CREATE SEQUENCE konyv_seq
START WITH 6
INCREMENT BY 1;

CREATE SEQUENCE kolcsonzes_seq
START WITH 6
INCREMENT BY 1;

CREATE SEQUENCE naplo_seq
START WITH 1
INCREMENT BY 1;